name: Update repository index

env:
  REPO_NAME: PKGBUILD
  RELEASE_NAME: repository
  KEY_FILE: signing.key.enc

on:
  # Run when repository files are updated
  push:
    paths:
      - 'files/**'
  # Allow manual trigger as well
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  updrepo:
    name: Update repository index
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master

      - uses: ./.github/actions/updrepo

      - uses: ./.github/actions/signrepo
        with:
          encryption_key: ${{secrets.ENCRYPTION_KEY}}
          encryption_iv: ${{secrets.ENCRYPTION_IV}}
          keyfile: ${{env.KEY_FILE}}
        continue-on-error: true

      - uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{secrets.GITHUB_TOKEN}}
          tag: ${{env.RELEASE_NAME}}
          file: 'repo/*'
          file_glob: true
          overwrite: true
